name: simpleclans-PLUS
main: simpleclans.simpleclans.SimpleclansPlugin
version: 1.2.0
api-version: 1.21
author: [Robin] #My name has to stay here you can add your own name like this [Robin, Yourname]
depend: [PlaceholderAPI]

commands:
  clan:
    description: Clan management command.
    usage: |
      /clan create <name> - Create a new clan.
      /clan invite <player> - Invite a player to your clan.
      /clan join <name> - Join a clan you were invited to.
      /clan leave - Leave your current clan.
      /clan info [name] - View clan info.
      /clan promote <player> - Promote a clan member.
      /clan demote <player> - Demote a clan member.
      /clan disband - Disband a clan.
      /clan update - update to the newset version.
      /clan chat - Toggle clan chat.
      /clan chatmsg - Send a message to your clan.
      /clan kick <player> - Kick a player from your team.
      /clan list - Lists all clans.
      /clan admin help - shows admin commands.
    aliases: [c]
    permission: simpleclans.use
    permission-message: You do not have permission to use this command.
permissions:
  simpleclans.use:
    description: Allows using general clan commands.
    default: true

  simpleclans.create:
    description: Allows players to create clans.
    default: true
    
  simpleclans.kick:
    description: Allows you to kick players from your clan.
    default: true
    
  simpleclans.invite:
    description: Allows inviting players to a clan.
    default: true

  simpleclans.join:
    description: Allows joining clans.
    default: true

  simpleclans.leave:
    description: Allows leaving your clan.
    default: true

  simpleclans.info:
    description: Allows viewing clan info.
    default: true

  simpleclans.promote:
    description: Allows promoting members in your clan.
    default: true

  simpleclans.demote:
    description: Allows demoting members in your clan.
    default: true

  simpleclans.disband:
    description: Allows disbanding your clan.
    default: true

  simpleclans.list:
    description: Allows listing online players and clans.
    default: true

  simpleclans.chatmsg:
    description: Allows sending single clan chat messages.
    default: true

  simpleclans.admin:
    description: Grants access to admin subcommands.
    default: op

  simpleclans.admin.promote:
    description: Admin promote command.
    default: op

  simpleclans.admin.demote:
    description: Admin demote command.
    default: op

  simpleclans.admin.kick:
    description: Admin kick command.
    default: op

  simpleclans.admin.disband:
    description: Admin disband command.
    default: op

  simpleclans.admin.reset:
    description: Admin reset clan command.
    default: op

  simpleclans.admin.purge:
    description: Admin purge player command.
    default: op

  simpleclans.admin.place:
    description: Admin place a player into a clan.
    default: op

  simpleclans.admin.invite:
    description: Admin invite a player to any clan.
    default: op

  simpleclans.admin.reload:
    description: Admin reload plugin config.
    default: op

