name: simpleclans-PLUS
main: simpleclans.simpleclans.SimpleclansPlugin
version: 1.0.0
api-version: 1.21
author: [Robin] #My name has to stay here you can add your own name like this [Robin, Yourname]
depend: [PlaceholderAPI]

commands:
  SimpleClansReload:
    description: Reloads the Plugin configuration.
    usage: /SimpleClansReload
    permission: simpleclansreload.admin
    permission-message: You do not have permission to use this command.
  clan:
    description: Clan management command.
    usage: |
      /clan create <name> - Create a new clan.
      /clan invite <player> - Invite a player to your clan.
      /clan join <name> - Join a clan you were invited to.
      /clan leave - Leave your current clan.
      /clan info [name] - View clan info.
      /clan promote <player> - Promote a clan member.
      /clan demote <player> - Demote a clan member.
      /clan disband - Disband a clan.
    permission: simpleclans.use
    permission-message: You do not have permission to use this command.

